/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PresentationPresentationsRouteImport } from './routes/_presentation/presentations'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as PresentationPresentationPresentationIdRouteImport } from './routes/_presentation/presentation.$presentationId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PresentationPresentationsRoute =
  PresentationPresentationsRouteImport.update({
    id: '/_presentation/presentations',
    path: '/presentations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationPresentationPresentationIdRoute =
  PresentationPresentationPresentationIdRouteImport.update({
    id: '/_presentation/presentation/$presentationId',
    path: '/presentation/$presentationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/presentations': typeof PresentationPresentationsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/presentation/$presentationId': typeof PresentationPresentationPresentationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/presentations': typeof PresentationPresentationsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/presentation/$presentationId': typeof PresentationPresentationPresentationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_presentation/presentations': typeof PresentationPresentationsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/_presentation/presentation/$presentationId': typeof PresentationPresentationPresentationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/presentations'
    | '/api/inngest'
    | '/presentation/$presentationId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/presentations'
    | '/api/inngest'
    | '/presentation/$presentationId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/login'
    | '/_presentation/presentations'
    | '/api/inngest'
    | '/_presentation/presentation/$presentationId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PresentationPresentationsRoute: typeof PresentationPresentationsRoute
  ApiInngestRoute: typeof ApiInngestRoute
  PresentationPresentationPresentationIdRoute: typeof PresentationPresentationPresentationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_presentation/presentations': {
      id: '/_presentation/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationPresentationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_presentation/presentation/$presentationId': {
      id: '/_presentation/presentation/$presentationId'
      path: '/presentation/$presentationId'
      fullPath: '/presentation/$presentationId'
      preLoaderRoute: typeof PresentationPresentationPresentationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PresentationPresentationsRoute: PresentationPresentationsRoute,
  ApiInngestRoute: ApiInngestRoute,
  PresentationPresentationPresentationIdRoute:
    PresentationPresentationPresentationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
